apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - scaledobject.yaml
configMapGenerator:
  - name: admin-console-config
    literals:
      - OIDC_ISSUER=http://localhost:8081/realms/cerbos-poc
      - OIDC_CLIENT_ID=patient-app
generatorOptions:
  disableNameSuffixHash: true
