apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - scaledobject.yaml
configMapGenerator:
  - name: ads-config
    literals:
      - ADS_HTTP_ADDR=:8080
      - CERBOS_GRPC_ADDR=cerbos:3593
      - POSTGRES_ADDR=postgres:5432
      - ADS_ROLE_MATRIX_CACHE_TTL=30s
      - KAFKA_BROKERS=redpanda:9092
      - KAFKA_PERMISSION_CHANGED_TOPIC=permission-changed
      - KAFKA_CONSUMER_GROUP=ads
      - ADS_RECONCILE_INTERVAL=2s
      - CAPABILITY_CATALOG_DIR=/capability-catalog
      - CAPABILITY_CATALOG_REVISION="1"
      - ROOT_POLICY_REVISION=root-v1.4.0
generatorOptions:
  disableNameSuffixHash: true
