apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ads
spec:
  scaleTargetRef:
    name: ads
  minReplicaCount: 2
  maxReplicaCount: 6
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "75"
