apiVersion: v1
kind: Service
metadata:
  name: cerbos
spec:
  selector:
    app: cerbos
  ports:
    - name: grpc
      port: 3593
      targetPort: 3593
    - name: http
      port: 3592
      targetPort: 3592
